#ifndef R8GE_EVENT_H
#define R8GE_EVENT_H

#include <string>

namespace r8ge {
    class Event {
    public:
        enum class EventType : unsigned char
        {
            NONE,

            // Generated by windows
            WINDOW_RESIZED, WINDOW_CLOSED, WINDOW_FOCUS, WINDOW_LOST_FOCUS, WINDOW_MOVED,
            KEY_PRESSED, KEY_RELEASED,
            MOUSE_PRESSED, MOUSE_RELEASED, MOUSE_MOVED, MOUSE_SCROLLED

            // Generated by the engine
        };

    public:
        Event();
        virtual ~Event();
        [[nodiscard]] EventType getType() const;
        [[nodiscard]] bool isHandled() const;
        void setToHandled();
        [[nodiscard]] std::string getTypeAsString() const;

    protected:
        struct {
            EventType type : 7;
            bool handled : 1;
        } m_header;
    };
}

#endif//!R8GE_EVENT_H
