#include "Strokes.h"

namespace r8ge {
    std::string to_string(const IOCode& code) {
        switch (code) {
            case IOCode::UNKNOWN: return "unknown";
            case IOCode::MBUTTON_1: return "mouse 1";
            case IOCode::MBUTTON_2: return "mouse 2";
            case IOCode::MBUTTON_3: return "mouse 3";
            case IOCode::MBUTTON_4: return "mouse 4";
            case IOCode::MBUTTON_5: return "mouse 5";
            case IOCode::MBUTTON_6: return "mouse 6";
            case IOCode::MBUTTON_7: return "mouse 7";
            case IOCode::MBUTTON_8: return "mouse 8";
            case IOCode::MBUTTON_LEFT: return "mouse left";
            case IOCode::MBUTTON_RIGHT: return "mouse right";
            case IOCode::MBUTTON_MIDDLE: return "mouse middle";
            case IOCode::SPACE: return "space";
            case IOCode::APOSTROPHE: return "\'";
            case IOCode::COMMA: return ",";
            case IOCode::MINUS: return "-";
            case IOCode::PERIOD: return ".";
            case IOCode::SLASH: return "/";
            case IOCode::N0: return "0";
            case IOCode::N1: return "1";
            case IOCode::N2: return "2";
            case IOCode::N3: return "3";
            case IOCode::N4: return "4";
            case IOCode::N5: return "5";
            case IOCode::N6: return "6";
            case IOCode::N7: return "7";
            case IOCode::N8: return "8";
            case IOCode::N9: return "9";
            case IOCode::SEMICOLON: return ";";
            case IOCode::EQUAL: return "=";
            case IOCode::A: return "A";
            case IOCode::B: return "B";
            case IOCode::C: return "C";
            case IOCode::D: return "D";
            case IOCode::E: return "E";
            case IOCode::F: return "F";
            case IOCode::G: return "G";
            case IOCode::H: return "H";
            case IOCode::I: return "I";
            case IOCode::J: return "J";
            case IOCode::K: return "K";
            case IOCode::L: return "L";
            case IOCode::M: return "M";
            case IOCode::N: return "N";
            case IOCode::O: return "O";
            case IOCode::P: return "P";
            case IOCode::Q: return "Q";
            case IOCode::R: return "R";
            case IOCode::S: return "S";
            case IOCode::T: return "T";
            case IOCode::U: return "U";
            case IOCode::V: return "V";
            case IOCode::W: return "W";
            case IOCode::X: return "X";
            case IOCode::Y: return "Y";
            case IOCode::Z: return "Z";
            case IOCode::LEFT_BRACKET: return "[";
            case IOCode::BACKSLASH: return "\\";
            case IOCode::RIGHT_BRACKET: return "]";
            case IOCode::GRAVE_ACCENT: return "`";
            case IOCode::ESCAPE: return "ESC";
            case IOCode::ENTER: return "enter";
            case IOCode::TAB: return "tab";
            case IOCode::BACKSPACE: return "backspace";
            case IOCode::INSERT: return "insert";
            case IOCode::DELETE: return "delete";
            case IOCode::RIGHT: return "right";
            case IOCode::LEFT: return "left";
            case IOCode::DOWN: return "down";
            case IOCode::UP: return "up";
            case IOCode::PAGE_UP: return "page up";
            case IOCode::PAGE_DOWN: return "page down";
            case IOCode::HOME: return "home";
            case IOCode::END: return "end";
            case IOCode::CAPS_LOCK: return "caps lock";
            case IOCode::SCROLL_LOCK: return "scroll lock";
            case IOCode::NUM_LOCK: return "num lock";
            case IOCode::PRINT_SCREEN: return "print screen";
            case IOCode::PAUSE: return "pause";
            case IOCode::F1: return "F1";
            case IOCode::F2: return "F2";
            case IOCode::F3: return "F3";
            case IOCode::F4: return "F4";
            case IOCode::F5: return "F5";
            case IOCode::F6: return "F6";
            case IOCode::F7: return "F7";
            case IOCode::F8: return "F8";
            case IOCode::F9: return "F9";
            case IOCode::F10: return "F10";
            case IOCode::F11: return "F11";
            case IOCode::F12: return "F12";
            case IOCode::F13: return "F13";
            case IOCode::F14: return "F14";
            case IOCode::F15: return "F15";
            case IOCode::F16: return "F16";
            case IOCode::F17: return "F17";
            case IOCode::F18: return "F18";
            case IOCode::F19: return "F19";
            case IOCode::F20: return "F20";
            case IOCode::F21: return "F21";
            case IOCode::F22: return "F22";
            case IOCode::F23: return "F23";
            case IOCode::F24: return "F24";
            case IOCode::F25: return "F25";
            case IOCode::KP_0: return "KP 0";
            case IOCode::KP_1: return "KP 1";
            case IOCode::KP_2: return "KP 2";
            case IOCode::KP_3: return "KP 3";
            case IOCode::KP_4: return "KP 4";
            case IOCode::KP_5: return "KP 5";
            case IOCode::KP_6: return "KP 6";
            case IOCode::KP_7: return "KP 7";
            case IOCode::KP_8: return "KP 8";
            case IOCode::KP_9: return "KP 9";
            case IOCode::KP_DECIMAL: return "KP decimal";
            case IOCode::KP_DIVIDE: return "KP divide";
            case IOCode::KP_MULTIPLY: return "KP multiply";
            case IOCode::KP_SUBTRACT: return "KP subtract";
            case IOCode::KP_ADD: return "KP add";
            case IOCode::KP_ENTER: return "KP enter";
            case IOCode::KP_EQUAL: return "KP equal";
            case IOCode::LEFT_SHIFT: return "left shift";
            case IOCode::LEFT_CONTROL: return "left control";
            case IOCode::LEFT_ALT: return "left alt";
            case IOCode::LEFT_SUPER: return "left super";
            case IOCode::RIGHT_SHIFT: return "right shift";
            case IOCode::RIGHT_CONTROL: return "right control";
            case IOCode::RIGHT_ALT: return "right alt";
            case IOCode::RIGHT_SUPER: return "right super";
            case IOCode::MENU: return "menu";
        }
        return "unknown";
    }
}